name: TubesZB MGM24PB Zigbee
device: MGM240PB32VNN
base_project: src/openthread_rcp
filename: "{manifest_name}_{ot_version}_{baudrate}"
sdk: "simplicity_sdk:2024.6.2"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: openthread_rcp
  ot_version: dynamic
  baudrate: 460800

c_defines:
  SL_UARTDRV_USART_VCOM_PERIPHERAL: USART0
  SL_UARTDRV_USART_VCOM_PERIPHERAL_NO: 0
  SL_UARTDRV_USART_VCOM_BAUDRATE: 460800

  SL_UARTDRV_USART_VCOM_TX_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_TX_PIN:  6

  SL_UARTDRV_USART_VCOM_RX_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_RX_PIN:  5

  SL_UARTDRV_USART_VCOM_CTS_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_CTS_PIN:  7

  SL_UARTDRV_USART_VCOM_RTS_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_RTS_PIN:  8

  SL_CLOCK_MANAGER_HFXO_EN: 1
  SL_CLOCK_MANAGER_HFXO_CTUNE: 140

  SL_RAIL_UTIL_RSSI_OFFSET: 0
