repos:
  - repo: local
    hooks:
      - id: normalize-cproject
        name: Normalize Eclipse .cproject files
        entry: python tools/normalize_cproject.py
        language: system
        files: \.cproject$
        pass_filenames: true
