[package]
name = "ohf-xncp-common"
edition.workspace = true
version.workspace = true

# Binds the zigbee stack itself: ohf-sys is also built for the RCP, which lacks it
[dependencies]
ohf-xncp = { path = "../ohf-xncp" }
ohf-xncp-macros = { path = "../ohf-xncp-macros" }
critical-section = "1"
linkme = "0.3"

[build-dependencies]
ohf-bindgen = { path = "../ohf-bindgen" }
ohf-config = { path = "../ohf-config" }
