//! WS2812 addressable RGB LED driver — Rust port of `ws2812.c`.
//!
//! Packs RGB into the WS2812 one-wire bit encoding and blasts it over SPI (EUSART
//! in SPI mode) via DMA. Exports the same C ABI the SDK LED framework and the LED
//! manager consume: `sl_led_ws2812`, `ws2812_led_driver_init`,
//! `ws2812_led_driver_refresh`.
#![no_std]

use core::cell::UnsafeCell;
use core::ffi::c_void;

use ohf_sys::{
    gpioModePushPull, ohf_gpio_pin_mode_set, sl_led_init, sl_led_rgb_pwm_t, sl_led_state_t,
    sl_led_t, sl_status_t, SPIDRV_Handle_t, SPIDRV_MTransmit, SL_LED_CURRENT_STATE_OFF,
    SL_LED_CURRENT_STATE_ON, SL_STATUS_OK,
};

// WS2812_NUM_LEDS / WS2812_EN_PIN / WS2812_EN_PORT, generated by build.rs from the
// manifest config build_project.py forwards (rust_build.json). Symbol-valued entries
// (e.g. WS2812_EN_PORT = SL_GPIO_PORT_C) resolve to ohf-sys bindgen consts.
include!(concat!(env!("OUT_DIR"), "/config.rs"));

const WS2812_BIT_0: u8 = 0b1000;
const WS2812_BIT_1: u8 = 0b1100;
const WS2812_BITS: usize = 4;
const RESET_SIGNAL_BYTES: usize = 20;
const SPI_BUFFER_SIZE: usize = RESET_SIGNAL_BYTES + 3 * (WS2812_NUM_LEDS * WS2812_BITS);

extern "C" {
    // Per-instance handle lives in the project's autogen, not the shared SDK, so it
    // is referenced (by name, opaque) here rather than in ohf-sys.
    static mut sl_spidrv_eusart_ws2812_handle: SPIDRV_Handle_t;
}

/// Single-core, no preemption of these statics beyond what the C original already
/// assumed. Wrap raw interior mutability so the statics can be `Sync`.
struct SyncCell<T>(UnsafeCell<T>);
unsafe impl<T> Sync for SyncCell<T> {}
impl<T> SyncCell<T> {
    const fn new(v: T) -> Self {
        Self(UnsafeCell::new(v))
    }
}

struct Context {
    red: u16,
    green: u16,
    blue: u16,
    dither_accum_red: u8,
    dither_accum_green: u8,
    dither_accum_blue: u8,
    state: sl_led_state_t,
}

static CTX: SyncCell<Context> = SyncCell::new(Context {
    red: 19275, // ~75/255 * 65535, dim white default
    green: 19275,
    blue: 19275,
    dither_accum_red: 0,
    dither_accum_green: 0,
    dither_accum_blue: 0,
    state: SL_LED_CURRENT_STATE_OFF as sl_led_state_t,
});

// First RESET_SIGNAL_BYTES stay zero (the WS2812 reset latch). 4-byte aligned for DMA.
#[repr(C, align(4))]
struct SpiBuf([u8; SPI_BUFFER_SIZE]);
static SPI_TX: SyncCell<SpiBuf> = SyncCell::new(SpiBuf([0; SPI_BUFFER_SIZE]));

// Precomputed 8-bit -> 4-byte SPI bit patterns, to avoid runtime bit twiddling.
static LOOKUP: SyncCell<[[u8; 4]; 256]> = SyncCell::new([[0; 4]; 256]);

fn precompute_ws2812_patterns(lookup: &mut [[u8; 4]; 256]) {
    for i in 0..256usize {
        for byte in 0..4usize {
            let bit_h = 7 - (2 * byte);
            let bit_l = bit_h - 1;
            let code_h = if i & (1 << bit_h) != 0 { WS2812_BIT_1 } else { WS2812_BIT_0 };
            let code_l = if i & (1 << bit_l) != 0 { WS2812_BIT_1 } else { WS2812_BIT_0 };
            lookup[i][byte] = (code_h << 4) | code_l;
        }
    }
}

/// Temporal dithering: flicker between two 8-bit values, tracking running error.
fn dither_channel(value: u16, accum: &mut u8) -> u8 {
    let base = (value >> 8) as u8;
    let frac = (value & 0xFF) as u8;

    let prev = *accum;
    *accum = accum.wrapping_add(frac);

    if *accum < prev {
        // overflow -> round up
        if base < 255 { base + 1 } else { 255 }
    } else {
        base
    }
}

unsafe fn apply_color() {
    let ctx = &mut *CTX.0.get();

    let (r, g, b) = if ctx.state == SL_LED_CURRENT_STATE_ON as sl_led_state_t {
        (
            dither_channel(ctx.red, &mut ctx.dither_accum_red),
            dither_channel(ctx.green, &mut ctx.dither_accum_green),
            dither_channel(ctx.blue, &mut ctx.dither_accum_blue),
        )
    } else {
        (0, 0, 0)
    };

    let lookup = &*LOOKUP.0.get();
    let buf = &mut (*SPI_TX.0.get()).0;

    // WS2812 wire order is G, R, B.
    let mut off = RESET_SIGNAL_BYTES;
    for _ in 0..WS2812_NUM_LEDS {
        buf[off..off + 4].copy_from_slice(&lookup[g as usize]);
        off += 4;
        buf[off..off + 4].copy_from_slice(&lookup[r as usize]);
        off += 4;
        buf[off..off + 4].copy_from_slice(&lookup[b as usize]);
        off += 4;
    }

    let handle = sl_spidrv_eusart_ws2812_handle;
    SPIDRV_MTransmit(
        handle,
        buf.as_ptr() as *const c_void,
        SPI_BUFFER_SIZE as core::ffi::c_int,
        None,
    );
}

// --- LED framework vtable callbacks. `context` is unused: there is one instance,
// so we reach the module statics directly, and the exported vtable carries null. ---
unsafe extern "C" fn ws2812_led_init(_context: *mut c_void) -> sl_status_t {
    ohf_gpio_pin_mode_set(WS2812_EN_PORT, WS2812_EN_PIN, gpioModePushPull as u32, 1);
    SL_STATUS_OK
}

unsafe extern "C" fn ws2812_led_turn_on(_context: *mut c_void) {
    (*CTX.0.get()).state = SL_LED_CURRENT_STATE_ON as sl_led_state_t;
}

unsafe extern "C" fn ws2812_led_turn_off(_context: *mut c_void) {
    (*CTX.0.get()).state = SL_LED_CURRENT_STATE_OFF as sl_led_state_t;
}

unsafe extern "C" fn ws2812_led_toggle(_context: *mut c_void) {
    let state = &mut (*CTX.0.get()).state;
    *state = if *state == SL_LED_CURRENT_STATE_ON as sl_led_state_t {
        SL_LED_CURRENT_STATE_OFF as sl_led_state_t
    } else {
        SL_LED_CURRENT_STATE_ON as sl_led_state_t
    };
}

unsafe extern "C" fn ws2812_led_get_state(_context: *mut c_void) -> sl_led_state_t {
    (*CTX.0.get()).state
}

unsafe extern "C" fn ws2812_led_set_color(_context: *mut c_void, red: u16, green: u16, blue: u16) {
    let ctx = &mut *CTX.0.get();
    ctx.red = red;
    ctx.green = green;
    ctx.blue = blue;
}

unsafe extern "C" fn ws2812_led_get_color(
    _context: *mut c_void,
    red: *mut u16,
    green: *mut u16,
    blue: *mut u16,
) {
    let ctx = &*CTX.0.get();
    *red = ctx.red;
    *green = ctx.green;
    *blue = ctx.blue;
}

#[repr(transparent)]
pub struct Vtable(sl_led_rgb_pwm_t);
unsafe impl Sync for Vtable {}

#[no_mangle]
pub static sl_led_ws2812: Vtable = Vtable(sl_led_rgb_pwm_t {
    led_common: sl_led_t {
        context: core::ptr::null_mut(),
        init: Some(ws2812_led_init),
        turn_on: Some(ws2812_led_turn_on),
        turn_off: Some(ws2812_led_turn_off),
        toggle: Some(ws2812_led_toggle),
        get_state: Some(ws2812_led_get_state),
    },
    set_rgb_color: Some(ws2812_led_set_color),
    get_rgb_color: Some(ws2812_led_get_color),
});

/// Refresh the LED hardware. Dithers the current color and blasts it to the LEDs.
/// Safe to call from ISR.
#[no_mangle]
pub extern "C" fn ws2812_led_driver_refresh() {
    unsafe { apply_color() }
}

#[no_mangle]
pub extern "C" fn ws2812_led_driver_init() {
    unsafe {
        precompute_ws2812_patterns(&mut *LOOKUP.0.get());
        sl_led_init(&sl_led_ws2812.0.led_common as *const sl_led_t);
    }
}
