name: SLZB-07Mg24 Zigbee
device: EFR32MG24A020F1024IM40
base_project: src/zigbee_ncp
filename: "{manifest_name}_{ezsp_version}_{baudrate}"
sdk: "simplicity_sdk:2024.6.2"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: zigbee_ncp
  ezsp_version: dynamic
  baudrate: 115200

configuration:
  SL_ZIGBEE_CHILD_TABLE_SIZE: 32

slcp_defines:
  SL_ZIGBEE_ADDRESS_TABLE_SIZE: 32
  SL_ZIGBEE_MULTICAST_TABLE_SIZE: 26
  SL_ZIGBEE_ROUTE_TABLE_SIZE: 16
  SL_ZIGBEE_DISCOVERY_TABLE_SIZE: 8

c_defines:
  SL_ZIGBEE_APS_UNICAST_MESSAGE_COUNT: 128
  SL_ZIGBEE_BINDING_TABLE_SIZE: 64
  SL_ZIGBEE_NEIGHBOR_TABLE_SIZE: 26
  SL_ZIGBEE_BROADCAST_TABLE_SIZE: 64
  SL_ZIGBEE_KEY_TABLE_SIZE: 12
  SL_ZIGBEE_MAX_END_DEVICE_CHILDREN: 64
  SL_ZIGBEE_SOURCE_ROUTE_TABLE_SIZE: 254
  SL_ZIGBEE_APS_DUPLICATE_REJECTION_MAX_ENTRIES: 64

  SL_IOSTREAM_USART_VCOM_BAUDRATE: 115200
  SL_IOSTREAM_USART_VCOM_FLOW_CONTROL_TYPE: usartHwFlowControlCtsAndRts
  SL_IOSTREAM_USART_VCOM_PERIPHERAL: USART0
  SL_IOSTREAM_USART_VCOM_PERIPHERAL_NO: 0

  SL_IOSTREAM_USART_VCOM_TX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_TX_PIN:  6

  SL_IOSTREAM_USART_VCOM_RX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_RX_PIN:  5

  SL_IOSTREAM_USART_VCOM_CTS_PORT: gpioPortB
  SL_IOSTREAM_USART_VCOM_CTS_PIN:  1

  SL_IOSTREAM_USART_VCOM_RTS_PORT: gpioPortB
  SL_IOSTREAM_USART_VCOM_RTS_PIN:  0

  SL_CLOCK_MANAGER_HFXO_EN: 1
  SL_CLOCK_MANAGER_HFXO_CTUNE: 140
  SL_CLOCK_MANAGER_DEFAULT_HF_CLOCK_SOURCE: SL_CLOCK_MANAGER_DEFAULT_HF_CLOCK_SOURCE_HFXO

