name: SLZB-MRW Z-Wave
device: EFR32ZG23A020F512GM40
base_project: src/zwave_ncp
filename: "{manifest_name}_{zwave_version}"
sdk: "simplicity_sdk:2024.6.2"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: zwave_ncp
  zwave_version: dynamic
  baudrate: 115200
  compression: lz4

c_defines:
  ZAF_CONFIG_MANUFACTURER_ID: "0x0466"
  ZAF_CONFIG_PRODUCT_TYPE_ID: "0x0001"
  ZAF_CONFIG_PRODUCT_ID: "0x0001"

  SERIAL_API_PERIPHERAL: USART0
  SERIAL_API_PERIPHERAL_NO: 0

  SERIAL_API_TX_PORT: gpioPortA
  SERIAL_API_TX_PIN:  5

  SERIAL_API_RX_PORT: gpioPortA
  SERIAL_API_RX_PIN:  6

  ZW_REGION: REGION_EU