#ifndef CONFIG_INTERNAL_APP_CONFIG_H_
#define CONFIG_INTERNAL_APP_CONFIG_H_

#ifndef CPC_SECONDARY_APP_VERSION_SUFFIX
#define CPC_SECONDARY_APP_VERSION_SUFFIX  ""
#endif

#endif /* CONFIG_INTERNAL_APP_CONFIG_H_ */
