[package]
name = "ohf-router"
edition.workspace = true
version.workspace = true

[features]
beacon_filter = []
eui64_unique = []
nvram_reset = ["dep:ohf-sys"]
install_code = ["dep:ohf-sys"]

[dependencies]
ohf-sys = { path = "../ohf-sys", features = ["factory_erase", "tokens"], optional = true }

[build-dependencies]
ohf-bindgen = { path = "../ohf-bindgen" }
