[package]
name = "xncp_common_commands"
edition.workspace = true
version.workspace = true

# Components this crate uses come from the slcc's `requires`
[dependencies]
critical-section = "1"
linkme = "0.3"

[build-dependencies]
ohf-bindgen = { path = "../ohf-bindgen" }
ohf-config = { path = "../ohf-config" }
