//! ZBT-2 pin-hole reset button. Holding it blinks 1, 2, … times, and completing
//! `ZBT2_RESET_BUTTON_CYCLES` cycles resets the adapter. Releasing early cancels.
#![no_std]

use core::cell::RefCell;
use core::ffi::c_void;

use critical_section::Mutex;
use led_effects_base::{clear_pattern, color, set_color, Priority};
use ohf_sys::{
    sl_sleeptimer_ms32_to_tick, sl_sleeptimer_start_timer, sl_sleeptimer_stop_timer,
    sl_sleeptimer_timer_callback_t, sl_sleeptimer_timer_handle_t, SyncCell, ZERO_TIMER,
};

#[allow(
    non_camel_case_types,
    non_upper_case_globals,
    non_snake_case,
    dead_code
)]
mod bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}
use bindings::*;

// Generated by build.rs from the component's rust_config
include!(concat!(env!("OUT_DIR"), "/config.rs"));

// From the project's autogen
extern "C" {
    static sl_button_pin_hole_button: sl_button_t;
}

struct State {
    reset_cycle: u8,
    blink_count: u8,
    led_on: bool,
}

static STATE: Mutex<RefCell<State>> = Mutex::new(RefCell::new(State {
    reset_cycle: 0,
    blink_count: 0,
    led_on: false,
}));

static RESET_TIMER: SyncCell<sl_sleeptimer_timer_handle_t> = SyncCell::new(ZERO_TIMER);
static BLINK_TIMER: SyncCell<sl_sleeptimer_timer_handle_t> = SyncCell::new(ZERO_TIMER);

fn start_ms(
    timer: &SyncCell<sl_sleeptimer_timer_handle_t>,
    timeout_ms: u32,
    callback: sl_sleeptimer_timer_callback_t,
) {
    let mut ticks: u32 = 0;
    unsafe {
        sl_sleeptimer_ms32_to_tick(timeout_ms, &mut ticks);
        sl_sleeptimer_start_timer(timer.get(), ticks, callback, core::ptr::null_mut(), 0, 0);
    }
}

fn stop(timer: &SyncCell<sl_sleeptimer_timer_handle_t>) {
    unsafe { sl_sleeptimer_stop_timer(timer.get()) };
}

#[cfg(feature = "zigbee_token_reset")]
fn reset_adapter() -> ! {
    set_color(Priority::Reset, color::RESET_ORANGE);
    unsafe {
        // Keeps the frame counters and boot counter
        sl_zigbee_token_factory_reset(true, true);
        ohf_sys::ohf_system_reset()
    }
}

#[cfg(not(feature = "zigbee_token_reset"))]
fn reset_adapter() -> ! {
    set_color(Priority::Reset, color::RESET_RED);
    ohf_sys::factory_erase()
}

extern "C" fn reset_timer_callback(_handle: *mut sl_sleeptimer_timer_handle_t, _data: *mut c_void) {
    critical_section::with(|cs| STATE.borrow(cs).borrow_mut().reset_cycle += 1);
    start_ms(
        &BLINK_TIMER,
        ZBT2_RESET_BUTTON_BLINK_START_DELAY_MS,
        Some(blink_task),
    );
}

extern "C" fn blink_task(_handle: *mut sl_sleeptimer_timer_handle_t, _data: *mut c_void) {
    let led_on = critical_section::with(|cs| STATE.borrow(cs).borrow().led_on);

    if led_on {
        // Reveal the layer below
        clear_pattern(Priority::Reset);

        let cycle_done = critical_section::with(|cs| {
            let mut s = STATE.borrow(cs).borrow_mut();
            s.led_on = false;
            if s.blink_count >= s.reset_cycle {
                s.blink_count = 0;
                Some(s.reset_cycle == ZBT2_RESET_BUTTON_CYCLES as u8)
            } else {
                None
            }
        });

        match cycle_done {
            Some(true) => reset_adapter(),
            Some(false) => start_ms(
                &RESET_TIMER,
                ZBT2_RESET_BUTTON_CYCLE_DELAY_MS,
                Some(reset_timer_callback),
            ),
            None => start_ms(
                &BLINK_TIMER,
                ZBT2_RESET_BUTTON_BLINK_OFF_MS,
                Some(blink_task),
            ),
        }
    } else {
        set_color(Priority::Reset, color::RESET_ORANGE);
        critical_section::with(|cs| {
            let mut s = STATE.borrow(cs).borrow_mut();
            s.led_on = true;
            s.blink_count += 1;
        });
        start_ms(
            &BLINK_TIMER,
            ZBT2_RESET_BUTTON_BLINK_ON_MS,
            Some(blink_task),
        );
    }
}

fn handle_state(pressed: bool) {
    stop(&RESET_TIMER);
    stop(&BLINK_TIMER);

    if pressed {
        critical_section::with(|cs| {
            let mut s = STATE.borrow(cs).borrow_mut();
            s.reset_cycle = 0;
            s.blink_count = 0;
            s.led_on = false;
        });
        start_ms(
            &RESET_TIMER,
            ZBT2_RESET_BUTTON_CYCLE_DELAY_MS,
            Some(reset_timer_callback),
        );
    } else {
        // Released early
        clear_pattern(Priority::Reset);
        critical_section::with(|cs| STATE.borrow(cs).borrow_mut().led_on = false);
    }
}

// Overrides the SDK's weak default
#[no_mangle]
pub unsafe extern "C" fn sl_button_on_change(handle: *const sl_button_t) {
    if handle == core::ptr::addr_of!(sl_button_pin_hole_button) {
        let pressed = sl_button_get_state(handle) == SL_SIMPLE_BUTTON_PRESSED as sl_button_state_t;
        handle_state(pressed);
    }
}
