name: SkyConnect Bootloader
device: EFR32MG21A020F512IM32
base_project: src/bootloader-uart-xmodem
filename: "{manifest_name}_{gecko_bootloader_version}"

gbl:
  fw_type: gecko-bootloader
  dynamic: ["gecko_bootloader_version"]
  baudrate: 115200

remove_components:
  - id: bootloader_gpio_activation

c_defines:
  SL_SERIAL_UART_FLOW_CONTROL: 1

  SL_SERIAL_UART_PERIPHERAL: USART0
  SL_SERIAL_UART_PERIPHERAL_NO: 0

  SL_SERIAL_UART_TX_PORT: gpioPortA
  SL_SERIAL_UART_TX_PIN:  6

  SL_SERIAL_UART_RX_PORT: gpioPortA
  SL_SERIAL_UART_RX_PIN:  5

  SL_SERIAL_UART_CTS_PORT: gpioPortB
  SL_SERIAL_UART_CTS_PIN:  1

  SL_SERIAL_UART_RTS_PORT: gpioPortB
  SL_SERIAL_UART_RTS_PIN:  0
