//! Common XNCP command set — commands 0x0001..0x0009, shared by every coordinator.
#![no_std]

use core::cell::RefCell;
use core::ffi::{c_void, CStr};
use core::ptr::addr_of_mut;

use critical_section::Mutex;
use linkme::distributed_slice;

use ohf_xncp_macros::xncp_command;

use ohf_xncp::{
    Reader, ReplyBuf, Status, XncpResult, REPLY_PAYLOAD_LEN, XNCP_FEATURES,
    XNCP_FEATURE_BUILD_STRING, XNCP_FEATURE_CHIP_INFO, XNCP_FEATURE_COMBINED_SEND,
    XNCP_FEATURE_FLOW_CONTROL_TYPE, XNCP_FEATURE_MANUAL_SOURCE_ROUTE,
    XNCP_FEATURE_MEMBER_OF_ALL_GROUPS, XNCP_FEATURE_MFG_TOKEN_OVERRIDES,
    XNCP_FEATURE_RESTORE_ROUTE_TABLE,
};

#[allow(
    non_camel_case_types,
    non_upper_case_globals,
    non_snake_case,
    dead_code
)]
mod bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}
use bindings::*;

// Generated by build.rs from the component's rust_config
include!(concat!(env!("OUT_DIR"), "/config.rs"));

const XNCP_SEND_UNICAST_FLAG_EXTENDED_TIMEOUT: u8 = 1 << 0;
const XNCP_SEND_UNICAST_FLAG_SOURCE_ROUTE: u8 = 1 << 1;

const FLOW_CONTROL_TYPE_SOFTWARE: u8 = 0x00;
const FLOW_CONTROL_TYPE_HARDWARE: u8 = 0x01;

// sli_zigbee_route_table_entry_t.status values.
const ROUTE_ACTIVE: u8 = 0;
const ROUTE_UNUSED: u8 = 3;

const RELAY_COUNT: usize = SL_ZIGBEE_MAX_SOURCE_ROUTE_RELAY_COUNT as usize;
const TABLE_SIZE: usize = XNCP_MANUAL_SOURCE_ROUTE_TABLE_SIZE;

// bindgen emits string macros as NUL-terminated byte strings
const fn c_str(s: &'static [u8]) -> &'static [u8] {
    match CStr::from_bytes_with_nul(s) {
        Ok(s) => s.to_bytes(),
        Err(_) => panic!("not a C string"),
    }
}

/// A string that must fit in a reply after `offset` bytes. Call in a const context.
const fn reply_str(s: &'static [u8], offset: usize) -> &'static [u8] {
    assert!(
        offset + s.len() <= REPLY_PAYLOAD_LEN,
        "too long for an XNCP reply"
    );
    s
}

// Replaces the stack's definition, so the linker never pulls `sl_zigbee_version.c.obj`
// from the stack archive. LTO folds this value into the `getValue(VERSION_INFO)` handler.
#[no_mangle]
#[allow(non_upper_case_globals)]
pub static sl_zigbee_version: sl_zigbee_version_t = sl_zigbee_version_t {
    build: SL_ZIGBEE_BUILD_NUMBER as u16,
    major: SL_ZIGBEE_MAJOR_VERSION as u8,
    minor: SL_ZIGBEE_MINOR_VERSION as u8,
    patch: SL_ZIGBEE_PATCH_VERSION as u8,
    special: if XNCP_EZSP_VERSION_PATCH_NUM_OVERRIDE == 0xFF {
        SL_ZIGBEE_SPECIAL_VERSION as u8
    } else {
        XNCP_EZSP_VERSION_PATCH_NUM_OVERRIDE
    },
    type_: SL_ZIGBEE_VERSION_TYPE as u8,
};

// EmberZNet internal tables
extern "C" {
    // Sized by `sli_zigbee_route_table_size`
    static mut sli_zigbee_route_table: [sli_zigbee_route_table_entry_t; 0];
    static mut sli_zigbee_route_table_size: u8;
    static mut sli_zigbee_address_table_size: u8;
}

fn pseudo_random() -> u16 {
    unsafe { sl_zigbee_get_pseudo_random_number() }
}

fn address_table_size() -> u8 {
    unsafe { sli_zigbee_address_table_size }
}

#[derive(Clone, Copy)]
struct RouteEntry {
    destination: u16,
    next_hop: u16,
    status: u8,
    cost: u8,
}

fn route_table_size() -> u8 {
    unsafe { sli_zigbee_route_table_size }
}

fn route_entry_ptr(index: u8) -> *mut sli_zigbee_route_table_entry_t {
    assert!(index < route_table_size());
    unsafe {
        addr_of_mut!(sli_zigbee_route_table)
            .cast::<sli_zigbee_route_table_entry_t>()
            .add(index as usize)
    }
}

fn route_table_get(index: u8) -> RouteEntry {
    let e = unsafe { &*route_entry_ptr(index) };
    RouteEntry {
        destination: e.destination,
        next_hop: e.nextHop,
        status: e.status,
        cost: e.cost,
    }
}

fn route_table_set(index: u8, v: RouteEntry) {
    let e = unsafe { &mut *route_entry_ptr(index) };
    e.destination = v.destination;
    e.nextHop = v.next_hop;
    e.status = v.status;
    e.cost = v.cost;
    e.networkIndex = 0;
}

// The slot for a fake route: an existing entry for `destination`, else the last unused
// one, else a random one
fn find_free_routing_table_entry(destination: u16) -> u8 {
    let size = route_table_size();
    let mut unused = None;
    for i in 0..size {
        let e = route_table_get(i);
        if e.destination == destination {
            return i;
        } else if e.status == ROUTE_UNUSED {
            unused = Some(i);
        }
    }
    unused.unwrap_or_else(|| (pseudo_random() % size as u16) as u8)
}

#[derive(Clone, Copy)]
struct ManualSourceRoute {
    active: bool,
    destination: u16,
    num_relays: u8,
    relays: [u16; RELAY_COUNT],
}

const EMPTY_ROUTE: ManualSourceRoute = ManualSourceRoute {
    active: false,
    destination: 0,
    num_relays: 0,
    relays: [0; RELAY_COUNT],
};

static MANUAL_SOURCE_ROUTES: Mutex<RefCell<[ManualSourceRoute; TABLE_SIZE]>> =
    Mutex::new(RefCell::new([EMPTY_ROUTE; TABLE_SIZE]));

// Replaces the route for `node_id`, else takes the last free slot, else a random one.
// `relays` holds little-endian u16 node ids.
fn install_manual_source_route(node_id: u16, relays: &[u8]) -> XncpResult {
    if relays.len() % 2 != 0 || relays.len() / 2 > RELAY_COUNT {
        return Err(Status::BAD_ARGUMENT);
    }

    critical_section::with(|cs| {
        let mut routes = MANUAL_SOURCE_ROUTES.borrow(cs).borrow_mut();

        let index = routes
            .iter()
            .position(|r| r.active && r.destination == node_id)
            .or_else(|| routes.iter().rposition(|r| !r.active))
            .unwrap_or_else(|| pseudo_random() as usize % TABLE_SIZE);

        let route = &mut routes[index];
        for (slot, relay) in route.relays.iter_mut().zip(relays.chunks_exact(2)) {
            *slot = u16::from_le_bytes([relay[0], relay[1]]);
        }
        route.destination = node_id;
        route.num_relays = (relays.len() / 2) as u8;
        route.active = true;
    });

    Ok(())
}

#[xncp_command(0x0001)]
fn handle_set_source_route(req: &[u8], _reply: &mut ReplyBuf) -> XncpResult {
    let mut req = Reader::new(req);
    let node_id = req.u16_le()?;
    install_manual_source_route(node_id, req.rest())
}

#[xncp_command(0x0002)]
fn handle_get_mfg_token_override(req: &[u8], reply: &mut ReplyBuf) -> XncpResult {
    let &[token_id] = req else {
        return Err(Status::BAD_ARGUMENT);
    };
    let value = match token_id as u32 {
        SL_ZIGBEE_EZSP_MFG_STRING => const { reply_str(XNCP_MFG_MANUF_NAME, 0) },
        SL_ZIGBEE_EZSP_MFG_BOARD_NAME => const { reply_str(XNCP_MFG_BOARD_NAME, 0) },
        _ => return Err(Status::NOT_FOUND),
    };
    reply.push_bytes(value);
    Ok(())
}

#[xncp_command(0x0003)]
fn handle_get_build_string(_req: &[u8], reply: &mut ReplyBuf) -> XncpResult {
    reply.push_bytes(const { reply_str(XNCP_BUILD_STRING, 0) });
    Ok(())
}

#[xncp_command(0x0004)]
fn handle_get_flow_control_type(_req: &[u8], reply: &mut ReplyBuf) -> XncpResult {
    let flow = if XNCP_FLOW_CONTROL_TYPE == usartHwFlowControlCtsAndRts as u32 {
        FLOW_CONTROL_TYPE_HARDWARE
    } else {
        FLOW_CONTROL_TYPE_SOFTWARE
    };
    reply.push(flow);
    Ok(())
}

#[xncp_command(0x0005)]
fn handle_get_chip_info(_req: &[u8], reply: &mut ReplyBuf) -> XncpResult {
    reply.push_u32_le(RAM_MEM_SIZE as u32);
    // After {ram_size: u32 le, part_len: u8}
    let part = const { reply_str(c_str(PART_NUMBER), 5) };
    reply.push(part.len() as u8);
    reply.push_bytes(part);
    Ok(())
}

#[xncp_command(0x0006)]
fn handle_set_route_table_entry(req: &[u8], _reply: &mut ReplyBuf) -> XncpResult {
    let &[index, d0, d1, n0, n1, status, cost] = req else {
        return Err(Status::BAD_ARGUMENT);
    };
    if index >= route_table_size() {
        return Err(Status::BAD_ARGUMENT);
    }
    route_table_set(
        index,
        RouteEntry {
            destination: u16::from_le_bytes([d0, d1]),
            next_hop: u16::from_le_bytes([n0, n1]),
            status,
            cost,
        },
    );
    Ok(())
}

#[xncp_command(0x0007)]
fn handle_get_route_table_entry(req: &[u8], reply: &mut ReplyBuf) -> XncpResult {
    let &[index] = req else {
        return Err(Status::BAD_ARGUMENT);
    };
    if index >= route_table_size() {
        return Err(Status::BAD_ARGUMENT);
    }
    let e = route_table_get(index);
    reply.push_u16_le(e.destination);
    reply.push_u16_le(e.next_hop);
    reply.push(e.status);
    reply.push(e.cost);
    Ok(())
}

struct TxPower {
    recommended_dbm: i8,
    max_dbm: i8,
    countries: &'static [[u8; 2]],
}

#[rustfmt::skip]
const TX_POWERS: &[TxPower] = &[
    // RED/ETSI-harmonized region: 10 dBm.
    TxPower {
        recommended_dbm: 10,
        max_dbm: 10,
        countries: &[
            // EU member states
            *b"AT", *b"BE", *b"BG", *b"HR", *b"CY", *b"CZ", *b"DK", *b"EE", *b"FI",
            *b"FR", *b"DE", *b"GR", *b"HU", *b"IE", *b"IT", *b"LV", *b"LT", *b"LU",
            *b"MT", *b"NL", *b"PL", *b"PT", *b"RO", *b"SK", *b"SI", *b"ES", *b"SE",
            // EEA members
            *b"IS", *b"LI", *b"NO",
            // Standards harmonized with RED or ETSI
            *b"CH", *b"GB", *b"TR", *b"AL", *b"BA", *b"GE", *b"MD", *b"ME", *b"MK",
            *b"RS", *b"UA",
            // Other CEPT nations
            *b"AD", *b"AZ", *b"MC", *b"SM", *b"VA",
        ]
    },
    // Testing: a max of 127 effectively disables the cap.
    TxPower {
        recommended_dbm: 8,
        max_dbm: 127,
        countries: &[*b"??"]
    },
];

#[xncp_command(0x0008)]
fn handle_get_tx_power_info(req: &[u8], reply: &mut ReplyBuf) -> XncpResult {
    let Ok(code) = <[u8; 2]>::try_from(req) else {
        return Err(Status::BAD_ARGUMENT);
    };

    let (recommended, max) = TX_POWERS
        .iter()
        .find(|p| p.countries.contains(&code))
        .map(|p| (p.recommended_dbm, p.max_dbm))
        .unwrap_or((
            XNCP_DEFAULT_RECOMMENDED_TX_POWER_DBM,
            XNCP_DEFAULT_MAX_TX_POWER_DBM,
        ));

    reply.push(recommended as u8);
    reply.push(max as u8);
    Ok(())
}

// Like the host's set_extended_timeout: creates an address table entry if none exists
fn apply_extended_timeout(mut eui64: [u8; 8], node_id: u16, extended_timeout: bool) {
    let eui = eui64.as_mut_ptr();

    let current = unsafe { sl_zigbee_get_extended_timeout(eui) } == SL_STATUS_OK;
    if current == extended_timeout {
        return;
    }

    let mut existing_node_id: u16 = 0;
    let found = unsafe { sl_zigbee_lookup_node_id_by_eui64(eui, &mut existing_node_id) };
    if found == SL_STATUS_OK && existing_node_id != SL_ZIGBEE_TABLE_ENTRY_UNUSED_NODE_ID as u16 {
        unsafe { sl_zigbee_set_extended_timeout(eui, extended_timeout) };
        return;
    }

    // No address table entry exists; replace a random one so the timeout sticks.
    let index = (pseudo_random() % address_table_size() as u16) as u8;
    unsafe {
        sl_zigbee_set_address_table_info(index, eui, node_id);
        sl_zigbee_set_extended_timeout(eui, extended_timeout);
    }
}

fn send_unicast(
    destination: u16,
    aps: &mut sl_zigbee_aps_frame_t,
    tag: u16,
    message: &[u8],
) -> (u32, u8) {
    let mut aps_sequence: u8 = 0;
    let status = unsafe {
        sl_zigbee_send_unicast(
            SL_ZIGBEE_OUTGOING_DIRECT as _,
            destination,
            aps,
            tag,
            message.len() as u8,
            message.as_ptr(),
            &mut aps_sequence,
        )
    };
    (status, aps_sequence)
}

#[xncp_command(0x0009)]
fn handle_send_unicast(req: &[u8], reply: &mut ReplyBuf) -> XncpResult {
    let mut req = Reader::new(req);
    let flags = req.u8()?;
    let destination = req.u16_le()?;
    let mut aps_frame = sl_zigbee_aps_frame_t {
        profileId: req.u16_le()?,
        clusterId: req.u16_le()?,
        sourceEndpoint: req.u8()?,
        destinationEndpoint: req.u8()?,
        options: req.u16_le()? as _,
        groupId: req.u16_le()?,
        sequence: req.u8()?,
        radius: 0,
    };
    let message_tag = req.u8()?;

    // Parse everything before acting on any of it
    let extended_timeout = if flags & XNCP_SEND_UNICAST_FLAG_EXTENDED_TIMEOUT != 0 {
        Some((req.array::<8>()?, req.u8()? != 0))
    } else {
        None
    };
    let relays = if flags & XNCP_SEND_UNICAST_FLAG_SOURCE_ROUTE != 0 {
        let num_relays = req.u8()? as usize;
        if num_relays > RELAY_COUNT {
            return Err(Status::BAD_ARGUMENT);
        }
        Some(req.bytes(num_relays * 2)?)
    } else {
        None
    };
    let message = req.rest();

    if let Some((eui64, enabled)) = extended_timeout {
        apply_extended_timeout(eui64, destination, enabled);
    }
    if let Some(relays) = relays {
        install_manual_source_route(destination, relays)?;
    }

    let (status, aps_sequence) =
        send_unicast(destination, &mut aps_frame, message_tag as u16, message);
    reply.push_u32_le(status);
    reply.push(aps_sequence);
    Ok(())
}

// XNCP_FEATURE_MEMBER_OF_ALL_GROUPS: receive every group's packets
#[no_mangle]
pub extern "C" fn __wrap_sli_zigbee_am_multicast_member(_multicast_id: u16) -> bool {
    true
}

// The `append_to_linked_buffers(buf, data, len)` macro expands to `really_append(&buf, …)`;
// the callback hands us the header pointer, so that `&buf` is the pointer itself.
unsafe fn append_to_header(header: *mut sli_buffer_manager_buffer_t, data: &[u8]) {
    sl_legacy_buffer_manager_really_append_to_linked_buffers(
        header,
        data.as_ptr() as *mut u8,
        data.len() as u16,
        true,
    );
}

// `header` is a sli_buffer_manager_buffer_t* that the buffer manager updates in place
#[no_mangle]
pub unsafe extern "C" fn nc_zigbee_override_append_source_route(
    destination: u16,
    header: *mut c_void,
    consumed: *mut bool,
) {
    let header = header as *mut sli_buffer_manager_buffer_t;

    let route = critical_section::with(|cs| {
        let mut routes = MANUAL_SOURCE_ROUTES.borrow(cs).borrow_mut();
        let route = routes
            .iter_mut()
            .find(|r| r.active && r.destination == destination)?;

        // Single use, except for the empty routes below
        if route.num_relays != 0 {
            route.active = false;
        }
        Some(*route)
    });

    let Some(route) = route else {
        *consumed = false;
        return;
    };
    *consumed = true;

    // Empty source routes are invalid per the spec: drop a fake route into the stack's
    // route table so EmberZNet just sends the packet directly.
    if route.num_relays == 0 {
        route_table_set(
            find_free_routing_table_entry(destination),
            RouteEntry {
                destination,
                next_hop: destination,
                status: ROUTE_ACTIVE,
                cost: 0,
            },
        );
        return;
    }

    // {relay count, relay index, relays in reverse order}
    append_to_header(header, &[route.num_relays, route.num_relays - 1]);
    for relay in route.relays[..route.num_relays as usize].iter().rev() {
        append_to_header(header, &relay.to_le_bytes());
    }
}

#[distributed_slice(XNCP_FEATURES)]
static COMMON_FEATURES: u32 = XNCP_FEATURE_MEMBER_OF_ALL_GROUPS
    | XNCP_FEATURE_MANUAL_SOURCE_ROUTE
    | XNCP_FEATURE_MFG_TOKEN_OVERRIDES
    | XNCP_FEATURE_BUILD_STRING
    | XNCP_FEATURE_FLOW_CONTROL_TYPE
    | XNCP_FEATURE_CHIP_INFO
    | XNCP_FEATURE_RESTORE_ROUTE_TABLE
    | XNCP_FEATURE_COMBINED_SEND;
