name: Qualcomm/WNC Freedom Bootloader
device: EFR32MG21A020F512IM32
base_project: src/bootloader
filename: "{manifest_name}_{gecko_bootloader_version}"
sdk: "gecko_sdk:4.4.4"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: gecko-bootloader
  gecko_bootloader_version: dynamic
  baudrate: 115200

c_defines:
  SL_BTL_BUTTON_PIN: 4
  SL_BTL_BUTTON_PORT: gpioPortC

  SL_SERIAL_UART_PERIPHERAL: USART1
  SL_SERIAL_UART_PERIPHERAL_NO: 1

  SL_SERIAL_UART_TX_PORT: gpioPortA
  SL_SERIAL_UART_TX_PIN:  5

  SL_SERIAL_UART_RX_PORT: gpioPortA
  SL_SERIAL_UART_RX_PIN:  6
