//! LED effects + manager — Rust port of `led_effects.c` + `led_manager.c` (the shared
//! `led_effects_base` component used by both Zigbee and Thread).
//!
//! The priority-layered LED state machine and the tilt monitor. The `layers` state is
//! touched from both main context (set/clear/update) and the tilt sleeptimer ISR, so it
//! lives behind a `critical_section::Mutex<RefCell<..>>`: the compiler only lets you
//! reach it while interrupts are masked, closing a race the C left open (it read
//! `layers` in `update_led_hardware` with no lock).
//!
//! The public C ABI (`led_manager.h` / `led_effects.h`) is preserved for the C callers
//! (zbt2_router_callbacks, zbt2_reset_button, the per-stack wrappers): the `#[repr(C)]`
//! types below mirror that header, which stays as the contract.
#![no_std]

use core::cell::{RefCell, UnsafeCell};
use core::ffi::c_void;
use core::sync::atomic::{AtomicBool, AtomicU32, Ordering};

use critical_section::Mutex;
use ohf_sys::{
    sl_led_rgb_pwm_t, sl_led_set_rgb_color, sl_led_t, sl_led_turn_off, sl_led_turn_on,
    sl_sleeptimer_start_periodic_timer_ms, sl_sleeptimer_stop_timer, sl_sleeptimer_timer_handle_t,
};

// Generated by build.rs: LED_EFFECTS_UPDATE_INTERVAL_MS / _TILT_THRESHOLD_DEG / _HYSTERESIS_DEG.
include!(concat!(env!("OUT_DIR"), "/config.rs"));

// --- C ABI types (mirror led_manager.h / led_manager_colors.h, the shared contract) ---
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Rgb {
    pub r: u16,
    pub g: u16,
    pub b: u16,
}

// led_mode_t / led_priority_t are C enums (int-sized). We take them across FFI as the
// raw u32 and validate, rather than as Rust enums, so an out-of-range value from C is a
// handled no-op instead of undefined behavior.
const LED_MODE_OFF: u32 = 0;
const LED_MODE_STATIC: u32 = 1;
const LED_MODE_BLINK: u32 = 2;
const LED_MODE_PULSE: u32 = 3;

const LED_PRIORITY_BACKGROUND: u32 = 0;
/// Tilt / factory-reset layer. Exported so the reset-button component can drive it.
pub const LED_PRIORITY_CRITICAL: u32 = 3;
const LED_PRIORITY_COUNT: usize = 4;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct LedPattern {
    pub mode: u32,
    pub color: Rgb,
    pub period_ms: u16,
    pub duration_ms: u32,
    pub brightness_min: u16,
    pub brightness_max: u16,
}

const fn rgb8(r: u8, g: u8, b: u8) -> Rgb {
    Rgb { r: r as u16 * 257, g: g as u16 * 257, b: b as u16 * 257 }
}
const LED_COLOR_WHITE_DIM: Rgb = rgb8(75, 75, 75);
// Factory-reset feedback colors (led_manager_colors.h), used by the reset-button component.
pub const LED_COLOR_RESET_RED: Rgb = rgb8(255, 0, 0);
pub const LED_COLOR_RESET_ORANGE: Rgb = rgb8(255, 40, 0);

// --- External symbols resolved at the firmware link (via the aggregate) ---
extern "C" {
    static sl_led_ws2812: sl_led_rgb_pwm_t;
    fn ws2812_led_driver_refresh();
}

/// Single-context-or-SDK-owned mutable statics (the sleeptimer handles the SDK writes
/// from ISR). Shared `layers` use the critical-section Mutex instead.
struct SyncCell<T>(UnsafeCell<T>);
unsafe impl<T> Sync for SyncCell<T> {}
impl<T> SyncCell<T> {
    const fn new(v: T) -> Self {
        Self(UnsafeCell::new(v))
    }
    fn get(&self) -> *mut T {
        self.0.get()
    }
}

const ZERO_TIMER: sl_sleeptimer_timer_handle_t = sl_sleeptimer_timer_handle_t {
    callback_data: core::ptr::null_mut(),
    priority: 0,
    option_flags: 0,
    next: core::ptr::null_mut(),
    callback: None,
    timeout_periodic: 0,
    delta: 0,
    timeout_expected_tc: 0,
    conversion_error: 0,
    accumulated_error: 0,
};

#[derive(Clone, Copy)]
struct Layer {
    pattern: LedPattern,
    active: bool,
    start_tick: u32,
    expiry_tick: u32,
}

const ZERO_LAYER: Layer = Layer {
    pattern: LedPattern {
        mode: LED_MODE_OFF,
        color: rgb8(0, 0, 0),
        period_ms: 0,
        duration_ms: 0,
        brightness_min: 0,
        brightness_max: 0,
    },
    active: false,
    start_tick: 0,
    expiry_tick: 0,
};

// --- Manager state ---
static LAYERS: Mutex<RefCell<[Layer; LED_PRIORITY_COUNT]>> =
    Mutex::new(RefCell::new([ZERO_LAYER; LED_PRIORITY_COUNT]));
static GLOBAL_TICK: AtomicU32 = AtomicU32::new(0);
static UPDATE_NEEDED: AtomicBool = AtomicBool::new(false);
static MANAGER_INITIALIZED: AtomicBool = AtomicBool::new(false);
static LED_TIMER: SyncCell<sl_sleeptimer_timer_handle_t> = SyncCell::new(ZERO_TIMER);

// --- Effects state ---
static TILT_TIMER: SyncCell<sl_sleeptimer_timer_handle_t> = SyncCell::new(ZERO_TIMER);
static MONITOR_TICKS: AtomicU32 = AtomicU32::new(0);
static IS_MONITORING: AtomicBool = AtomicBool::new(false);
static WAS_TILTED: AtomicBool = AtomicBool::new(false);

fn led_common() -> *const sl_led_t {
    unsafe { &sl_led_ws2812.led_common as *const sl_led_t }
}

fn set_rgb(color: Rgb) {
    unsafe {
        sl_led_set_rgb_color(&sl_led_ws2812, color.r, color.g, color.b);
        sl_led_turn_on(led_common());
    }
}

extern "C" fn led_timer_callback(_handle: *mut sl_sleeptimer_timer_handle_t, _data: *mut c_void) {
    GLOBAL_TICK.fetch_add(1, Ordering::SeqCst);
    UPDATE_NEEDED.store(true, Ordering::SeqCst);
    unsafe { ws2812_led_driver_refresh() }
}

fn update_led_hardware() {
    // Pick the highest active, non-expired layer (and retire expired ones) under the CS.
    let selected = critical_section::with(|cs| {
        let mut layers = LAYERS.borrow(cs).borrow_mut();
        let current_tick = GLOBAL_TICK.load(Ordering::SeqCst);
        let mut top: Option<usize> = None;
        for i in (0..LED_PRIORITY_COUNT).rev() {
            if !layers[i].active {
                continue;
            }
            if layers[i].pattern.duration_ms > 0 && current_tick >= layers[i].expiry_tick {
                layers[i].active = false;
                continue;
            }
            if top.is_none() {
                top = Some(i);
            }
        }
        top.map(|i| (layers[i].pattern, current_tick.wrapping_sub(layers[i].start_tick)))
    });

    let (p, layer_ticks) = match selected {
        Some(x) => x,
        None => {
            unsafe { sl_led_turn_off(led_common()) }
            return;
        }
    };

    let ms_elapsed = layer_ticks.wrapping_mul(LED_EFFECTS_UPDATE_INTERVAL_MS);

    match p.mode {
        LED_MODE_STATIC => set_rgb(p.color),
        LED_MODE_BLINK => {
            let period = if p.period_ms > 0 { p.period_ms as u32 } else { 500 };
            if (ms_elapsed % period) < period / 2 {
                set_rgb(p.color);
            } else {
                unsafe { sl_led_turn_off(led_common()) }
            }
        }
        LED_MODE_PULSE => {
            let period = if p.period_ms >= 2 { p.period_ms as u32 } else { 1000 };
            let half = period / 2;
            let phase = ms_elapsed % period;
            let tri = if phase < half {
                phase * 65535 / half
            } else {
                65535 - (phase - half) * 65535 / (period - half)
            };
            let (min_b, max_b) = (p.brightness_min as u32, p.brightness_max as u32);
            let brightness = min_b + (max_b - min_b) * tri / 65535;
            let scale = |c: u16| ((c as u32 * brightness) / 65535) as u16;
            set_rgb(Rgb { r: scale(p.color.r), g: scale(p.color.g), b: scale(p.color.b) });
        }
        // LED_MODE_OFF and any unknown mode
        _ => unsafe { sl_led_turn_off(led_common()) },
    }
}

#[no_mangle]
pub extern "C" fn led_manager_init() {
    if MANAGER_INITIALIZED.swap(true, Ordering::SeqCst) {
        return;
    }
    unsafe {
        sl_sleeptimer_start_periodic_timer_ms(
            LED_TIMER.get(),
            LED_EFFECTS_UPDATE_INTERVAL_MS,
            Some(led_timer_callback),
            core::ptr::null_mut(),
            0,
            0,
        );
    }
}

#[no_mangle]
pub extern "C" fn led_manager_process_action() {
    if UPDATE_NEEDED.swap(false, Ordering::SeqCst) {
        update_led_hardware();
    }
}

fn set_pattern(priority: u32, pattern: &LedPattern) {
    let pri = priority as usize;
    if pri >= LED_PRIORITY_COUNT {
        return;
    }
    critical_section::with(|cs| {
        let mut layers = LAYERS.borrow(cs).borrow_mut();
        let tick = GLOBAL_TICK.load(Ordering::SeqCst);
        layers[pri].pattern = *pattern;
        layers[pri].active = true;
        layers[pri].start_tick = tick;
        if pattern.duration_ms > 0 {
            layers[pri].expiry_tick = tick + pattern.duration_ms / LED_EFFECTS_UPDATE_INTERVAL_MS;
        }
    });
}

// C ABI for the still-C router callbacks (zbt2_router_callbacks.c); Rust uses set_pattern.
#[no_mangle]
pub extern "C" fn led_manager_set_pattern(priority: u32, pattern: *const LedPattern) {
    if let Some(pattern) = unsafe { pattern.as_ref() } {
        set_pattern(priority, pattern);
    }
}

#[no_mangle]
pub extern "C" fn led_manager_clear_pattern(priority: u32) {
    let pri = priority as usize;
    if pri >= LED_PRIORITY_COUNT {
        return;
    }
    critical_section::with(|cs| {
        LAYERS.borrow(cs).borrow_mut()[pri].active = false;
    });
}

#[no_mangle]
pub extern "C" fn led_manager_set_color(priority: u32, color: Rgb) {
    let pattern = LedPattern {
        mode: LED_MODE_STATIC,
        color,
        period_ms: 0,
        duration_ms: 0,
        brightness_min: 0,
        brightness_max: 0,
    };
    set_pattern(priority, &pattern);
}

fn calculate_tilt_angle() -> f32 {
    let [ax, ay, az] = ohf_qma6100p::read_acceleration();

    let total_mag = libm::sqrtf(ax * ax + ay * ay + az * az);
    if total_mag < 0.1 {
        return 0.0;
    }
    let horizontal_mag = libm::sqrtf(ax * ax + ay * ay);
    let tilt_rad = libm::asinf(horizontal_mag / total_mag);
    tilt_rad * 180.0 / core::f32::consts::PI
}

extern "C" fn tilt_monitor_callback(_handle: *mut sl_sleeptimer_timer_handle_t, _data: *mut c_void) {
    let ticks = MONITOR_TICKS.fetch_add(1, Ordering::SeqCst) + 1;

    // Check tilt every ~100ms (25 * UPDATE_INTERVAL_MS).
    if ticks % 25 != 0 {
        return;
    }

    let tilt_angle = calculate_tilt_angle();
    let was_tilted = WAS_TILTED.load(Ordering::SeqCst);
    let is_tilted = if was_tilted {
        tilt_angle > (LED_EFFECTS_TILT_THRESHOLD_DEG - LED_EFFECTS_TILT_HYSTERESIS_DEG)
    } else {
        tilt_angle > LED_EFFECTS_TILT_THRESHOLD_DEG
    };

    if is_tilted && !was_tilted {
        let tilt_pattern = LedPattern {
            mode: LED_MODE_BLINK,
            color: LED_COLOR_WHITE_DIM,
            period_ms: 500,
            duration_ms: 0,
            brightness_min: 0,
            brightness_max: 0,
        };
        set_pattern(LED_PRIORITY_CRITICAL, &tilt_pattern);
    } else if !is_tilted && was_tilted {
        led_manager_clear_pattern(LED_PRIORITY_CRITICAL);
    }
    WAS_TILTED.store(is_tilted, Ordering::SeqCst);
}

#[no_mangle]
pub extern "C" fn led_effects_init() {
    led_manager_init();
}

#[no_mangle]
pub extern "C" fn led_effects_set_network_state(network_formed: bool) {
    if network_formed {
        // Network formed: background off, stop tilt monitoring.
        led_manager_clear_pattern(LED_PRIORITY_BACKGROUND);
        if IS_MONITORING.swap(false, Ordering::SeqCst) {
            unsafe { sl_sleeptimer_stop_timer(TILT_TIMER.get()) };
            led_manager_clear_pattern(LED_PRIORITY_CRITICAL);
        }
    } else {
        // Searching: pulse white on the background layer, start tilt monitoring.
        let search_pattern = LedPattern {
            mode: LED_MODE_PULSE,
            color: LED_COLOR_WHITE_DIM,
            period_ms: 2760,
            duration_ms: 0,
            brightness_min: 6554, // ~10%
            brightness_max: 65535,
        };
        set_pattern(LED_PRIORITY_BACKGROUND, &search_pattern);

        if !IS_MONITORING.swap(true, Ordering::SeqCst) {
            MONITOR_TICKS.store(0, Ordering::SeqCst);
            WAS_TILTED.store(false, Ordering::SeqCst);
            unsafe {
                sl_sleeptimer_start_periodic_timer_ms(
                    TILT_TIMER.get(),
                    LED_EFFECTS_UPDATE_INTERVAL_MS,
                    Some(tilt_monitor_callback),
                    core::ptr::null_mut(),
                    0,
                    0,
                );
            }
        }
    }
}
