//! The priority-layered LED manager and the tilt monitor.
#![no_std]

use core::cell::RefCell;
use core::ffi::c_void;
use core::sync::atomic::{AtomicBool, AtomicU32, Ordering};

use critical_section::Mutex;
use ohf_sys::{
    sl_led_rgb_pwm_t, sl_led_set_rgb_color, sl_led_t, sl_led_turn_off, sl_led_turn_on,
    sl_sleeptimer_start_periodic_timer_ms, sl_sleeptimer_stop_timer, sl_sleeptimer_timer_handle_t,
    SyncCell, ZERO_TIMER,
};

// Generated by build.rs from the manifest config
include!(concat!(env!("OUT_DIR"), "/config.rs"));

#[derive(Clone, Copy)]
pub struct Rgb {
    pub r: u16,
    pub g: u16,
    pub b: u16,
}

impl Rgb {
    pub const fn rgb8(r: u8, g: u8, b: u8) -> Self {
        Self { r: r as u16 * 257, g: g as u16 * 257, b: b as u16 * 257 }
    }
}

pub mod color {
    use super::Rgb;

    pub const BLACK: Rgb = Rgb::rgb8(0, 0, 0);
    pub const WHITE_DIM: Rgb = Rgb::rgb8(75, 75, 75);
    pub const RESET_RED: Rgb = Rgb::rgb8(255, 0, 0);
    pub const RESET_ORANGE: Rgb = Rgb::rgb8(255, 40, 0);
    pub const SEARCH_BLUE: Rgb = Rgb::rgb8(0, 0, 75);
    pub const JOIN_GREEN: Rgb = Rgb::rgb8(0, 255, 0);
}

/// Higher layers hide lower ones while active
#[derive(Clone, Copy)]
pub enum Priority {
    /// Network state
    Background,
    /// User command or Zigbee light state
    Manual,
    /// Short feedback, such as joining or identify
    Notification,
    /// Tilt and factory reset
    Critical,
}

const PRIORITY_COUNT: usize = 4;

#[derive(Clone, Copy)]
pub enum Mode {
    Off,
    Static,
    /// On/off square wave
    Blink,
    /// Triangle wave fading between two brightnesses
    Pulse,
}

#[derive(Clone, Copy)]
pub struct Pattern {
    pub mode: Mode,
    pub color: Rgb,
    /// Cycle time for blink and pulse
    pub period_ms: u16,
    /// Clear the layer after this long, 0 for never
    pub duration_ms: u32,
    pub brightness_min: u16,
    pub brightness_max: u16,
}

impl Pattern {
    pub const OFF: Self = Self {
        mode: Mode::Off,
        color: color::BLACK,
        period_ms: 0,
        duration_ms: 0,
        brightness_min: 0,
        brightness_max: 0,
    };

    pub const fn solid(color: Rgb) -> Self {
        Self { mode: Mode::Static, color, ..Self::OFF }
    }

    pub const fn blink(color: Rgb, period_ms: u16) -> Self {
        Self { mode: Mode::Blink, color, period_ms, ..Self::OFF }
    }

    pub const fn pulse(color: Rgb, period_ms: u16, brightness_min: u16, brightness_max: u16) -> Self {
        Self { mode: Mode::Pulse, color, period_ms, brightness_min, brightness_max, ..Self::OFF }
    }

    pub const fn lasting(self, duration_ms: u32) -> Self {
        Self { duration_ms, ..self }
    }
}

// The network search pulse
const SEARCH_PULSE_PERIOD_MS: u16 = 2760;
const SEARCH_PULSE_MIN_BRIGHTNESS: u16 = 6554; // ~10%

extern "C" {
    static sl_led_ws2812: sl_led_rgb_pwm_t;
    fn ws2812_led_driver_refresh();
}

#[derive(Clone, Copy)]
struct Layer {
    pattern: Pattern,
    active: bool,
    start_tick: u32,
    expiry_tick: u32,
}

const ZERO_LAYER: Layer = Layer {
    pattern: Pattern::OFF,
    active: false,
    start_tick: 0,
    expiry_tick: 0,
};

// Also used from the sleeptimer ISRs
static LAYERS: Mutex<RefCell<[Layer; PRIORITY_COUNT]>> =
    Mutex::new(RefCell::new([ZERO_LAYER; PRIORITY_COUNT]));
static GLOBAL_TICK: AtomicU32 = AtomicU32::new(0);
static UPDATE_NEEDED: AtomicBool = AtomicBool::new(false);
static MANAGER_INITIALIZED: AtomicBool = AtomicBool::new(false);
static LED_TIMER: SyncCell<sl_sleeptimer_timer_handle_t> = SyncCell::new(ZERO_TIMER);

static TILT_TIMER: SyncCell<sl_sleeptimer_timer_handle_t> = SyncCell::new(ZERO_TIMER);
static MONITOR_TICKS: AtomicU32 = AtomicU32::new(0);
static IS_MONITORING: AtomicBool = AtomicBool::new(false);
static WAS_TILTED: AtomicBool = AtomicBool::new(false);

fn led_common() -> *const sl_led_t {
    unsafe { &sl_led_ws2812.led_common as *const sl_led_t }
}

fn set_rgb(color: Rgb) {
    unsafe {
        sl_led_set_rgb_color(&sl_led_ws2812, color.r, color.g, color.b);
        sl_led_turn_on(led_common());
    }
}

fn turn_off() {
    unsafe { sl_led_turn_off(led_common()) }
}

extern "C" fn led_timer_callback(_handle: *mut sl_sleeptimer_timer_handle_t, _data: *mut c_void) {
    GLOBAL_TICK.fetch_add(1, Ordering::SeqCst);
    UPDATE_NEEDED.store(true, Ordering::SeqCst);
    unsafe { ws2812_led_driver_refresh() }
}

fn update_led_hardware() {
    // Pick the highest active layer and retire expired ones
    let selected = critical_section::with(|cs| {
        let mut layers = LAYERS.borrow(cs).borrow_mut();
        let current_tick = GLOBAL_TICK.load(Ordering::SeqCst);
        let mut top: Option<usize> = None;
        for i in (0..PRIORITY_COUNT).rev() {
            if !layers[i].active {
                continue;
            }
            if layers[i].pattern.duration_ms > 0 && current_tick >= layers[i].expiry_tick {
                layers[i].active = false;
                continue;
            }
            if top.is_none() {
                top = Some(i);
            }
        }
        top.map(|i| (layers[i].pattern, current_tick.wrapping_sub(layers[i].start_tick)))
    });

    let Some((p, layer_ticks)) = selected else {
        turn_off();
        return;
    };

    let ms_elapsed = layer_ticks.wrapping_mul(LED_EFFECTS_UPDATE_INTERVAL_MS);

    match p.mode {
        Mode::Off => turn_off(),
        Mode::Static => set_rgb(p.color),
        Mode::Blink => {
            let period = if p.period_ms > 0 { p.period_ms as u32 } else { 500 };
            if (ms_elapsed % period) < period / 2 {
                set_rgb(p.color);
            } else {
                turn_off();
            }
        }
        Mode::Pulse => {
            let period = if p.period_ms >= 2 { p.period_ms as u32 } else { 1000 };
            let half = period / 2;
            let phase = ms_elapsed % period;
            let tri = if phase < half {
                phase * 65535 / half
            } else {
                65535 - (phase - half) * 65535 / (period - half)
            };
            let (min_b, max_b) = (p.brightness_min as u32, p.brightness_max as u32);
            let brightness = min_b + (max_b - min_b) * tri / 65535;
            let scale = |c: u16| ((c as u32 * brightness) / 65535) as u16;
            set_rgb(Rgb { r: scale(p.color.r), g: scale(p.color.g), b: scale(p.color.b) });
        }
    }
}

fn manager_init() {
    if MANAGER_INITIALIZED.swap(true, Ordering::SeqCst) {
        return;
    }
    unsafe {
        sl_sleeptimer_start_periodic_timer_ms(
            LED_TIMER.get(),
            LED_EFFECTS_UPDATE_INTERVAL_MS,
            Some(led_timer_callback),
            core::ptr::null_mut(),
            0,
            0,
        );
    }
}

// Registered by the led_effects_base component as a process action
#[no_mangle]
pub extern "C" fn led_manager_process_action() {
    if UPDATE_NEEDED.swap(false, Ordering::SeqCst) {
        update_led_hardware();
    }
}

pub fn set_pattern(priority: Priority, pattern: Pattern) {
    critical_section::with(|cs| {
        let layer = &mut LAYERS.borrow(cs).borrow_mut()[priority as usize];
        let tick = GLOBAL_TICK.load(Ordering::SeqCst);
        layer.pattern = pattern;
        layer.active = true;
        layer.start_tick = tick;
        if pattern.duration_ms > 0 {
            layer.expiry_tick = tick + pattern.duration_ms / LED_EFFECTS_UPDATE_INTERVAL_MS;
        }
    });
}

pub fn clear_pattern(priority: Priority) {
    critical_section::with(|cs| {
        LAYERS.borrow(cs).borrow_mut()[priority as usize].active = false;
    });
}

pub fn set_color(priority: Priority, color: Rgb) {
    set_pattern(priority, Pattern::solid(color));
}

// `asin(|horizontal| / |total|) > threshold`, compared as squared sines to avoid the
// trigonometry. Both sides are monotonic over 0-90 degrees.
fn is_tilted(threshold_sin2: f32) -> bool {
    let [ax, ay, az] = ohf_qma6100p::read_acceleration();
    let horizontal = ax * ax + ay * ay;
    let total = horizontal + az * az;
    total >= 0.01 && horizontal > threshold_sin2 * total
}

extern "C" fn tilt_monitor_callback(_handle: *mut sl_sleeptimer_timer_handle_t, _data: *mut c_void) {
    let ticks = MONITOR_TICKS.fetch_add(1, Ordering::SeqCst) + 1;

    // Check tilt every ~100ms (25 * UPDATE_INTERVAL_MS).
    if ticks % 25 != 0 {
        return;
    }

    let was_tilted = WAS_TILTED.load(Ordering::SeqCst);
    let is_tilted = is_tilted(if was_tilted {
        LED_EFFECTS_TILT_RELEASE_SIN2
    } else {
        LED_EFFECTS_TILT_THRESHOLD_SIN2
    });

    if is_tilted && !was_tilted {
        set_pattern(Priority::Critical, Pattern::blink(color::WHITE_DIM, 500));
    } else if !is_tilted && was_tilted {
        clear_pattern(Priority::Critical);
    }
    WAS_TILTED.store(is_tilted, Ordering::SeqCst);
}

pub fn init() {
    manager_init();
}

pub fn set_network_state(network_formed: bool) {
    if network_formed {
        // Network formed: background off, stop tilt monitoring.
        clear_pattern(Priority::Background);
        if IS_MONITORING.swap(false, Ordering::SeqCst) {
            unsafe { sl_sleeptimer_stop_timer(TILT_TIMER.get()) };
            clear_pattern(Priority::Critical);
        }
    } else {
        // Searching: pulse white on the background layer, start tilt monitoring.
        set_pattern(Priority::Background, search_pulse(color::WHITE_DIM));

        if !IS_MONITORING.swap(true, Ordering::SeqCst) {
            MONITOR_TICKS.store(0, Ordering::SeqCst);
            WAS_TILTED.store(false, Ordering::SeqCst);
            unsafe {
                sl_sleeptimer_start_periodic_timer_ms(
                    TILT_TIMER.get(),
                    LED_EFFECTS_UPDATE_INTERVAL_MS,
                    Some(tilt_monitor_callback),
                    core::ptr::null_mut(),
                    0,
                    0,
                );
            }
        }
    }
}

/// The network search pulse in the given color, for stacks that signal search phases
pub const fn search_pulse(color: Rgb) -> Pattern {
    Pattern::pulse(color, SEARCH_PULSE_PERIOD_MS, SEARCH_PULSE_MIN_BRIGHTNESS, 65535)
}
