name: Yellow build with external antenna enabled

on: workflow_dispatch

env:
  sdk_version: 4.4.0

jobs:
  build-container:
    name: Create build container image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    outputs:
      sdk_version: ${{ env.sdk_version }}
      image_name: ghcr.io/${{ steps.lower.outputs.repository_owner }}/silabs-firmware-builder:${{ env.sdk_version }}
    steps:
      - name: Repository owner lowercase
        id: lower
        run: |
          echo "repository_owner=$(echo $GITHUB_REPOSITORY_OWNER | tr [:upper:] [:lower:])" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3.3.0
      - name: Log in to the GitHub container registry
        uses: docker/login-action@v2.1.0
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Build and Push
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: Dockerfile
          tags: ghcr.io/${{ steps.lower.outputs.repository_owner }}/silabs-firmware-builder:${{ env.sdk_version }}
          cache-from: ghcr.io/${{ steps.lower.outputs.repository_owner }}/silabs-firmware-builder:cache-${{ env.sdk_version }}
          cache-to: ghcr.io/${{ steps.lower.outputs.repository_owner }}/silabs-firmware-builder:cache-${{ env.sdk_version }}
          push: true
          build-args:
            "GECKO_SDK_VERSION=v${{ env.sdk_version }}"

  ezsp-firmware-build:
    name: EmberZNet NCP
    needs: build-container
    strategy:
      matrix:
        include:
          - target: yellow-ext
            device: MGM210PA32JIA
            components: simple_led:board_activity,zigbee_token_interface,zigbee_mfglib
            patchpath: "EmberZNet/Yellow-ext"
    uses: ./.github/workflows/silabs-firmware-build.yaml
    with:
      image_name: ${{ needs.build-container.outputs.image_name }}
      firmware_name: ncp-uart-hw-${{ matrix.target }}
      project_file: "/gecko_sdk/protocol/zigbee/app/ncp/sample-app/ncp-uart-hw/ncp-uart-hw.slcp"
      project_name: "ncp-uart-hw"
      device: ${{ matrix.device }}
      components: ${{ matrix.components }}
      configuration:  |
        SL_IOSTREAM_USART_VCOM_RX_BUFFER_SIZE:64,
        EMBER_APS_UNICAST_MESSAGE_COUNT:20,
        EMBER_NEIGHBOR_TABLE_SIZE:26,
        EMBER_SOURCE_ROUTE_TABLE_SIZE:200,
      patchpath: ${{ matrix.patchpath }}
      extra_c_defs: "'-DEMBER_ADDRESS_TABLE_SIZE=16' '-DEMBER_MULTICAST_TABLE_SIZE=16'"
      sdk_version: ${{ needs.build-container.outputs.sdk_version }}
      metadata_fw_type: "ncp-uart-hw"
      baudrate: 115200
      metadata_extra: "{ \"ezsp_version\": \"7.4.0.0\" }"

